### ISSUE TITLE
API Usage Guidelines: empty space under the header

### ISSUE THREAD

**Issue by omelniko** [opentelekomcloud-docs/elastic-cloud-server#36] opened 2022-04-13 05:00 UTC
Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/api-ref/source/api_usage_guidelines.rst

![image](https://user-images.githubusercontent.com/102943925/163103603-68be8886-1dc7-451b-9dab-73a276f8233a.png)
Maybe it is not an issue, but empty space looks a bit strange

**Comment by vladimirhasko** [comment] 2022-04-25 09:43
this needs further investigation. The problem is related to breadcrumbs navigation

**Comment by vladimirhasko** [comment] 2023-03-03 07:39
the issue is fixed now

**Closed by vladimirhasko** 2023-03-03 07:39 UTC
